apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: artrails-ingress
  namespace: emontoya

spec:
  rules:
    - host: emontoya.dis.eafit.edu.co
      http:
        paths:
          - path: /
            backend:
              serviceName: artrails-webapp-service
              servicePort: 80
