apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-server
  namespace: emontoya
spec:
  replicas: 1
  selector:
    app: artrails-webapp
  template:
    metadata:
      name: postgres-server
      labels:
        app: artrails-webapp
        namespace: emontoya

    spec:
      containers:
      - name: postgres
        image: postgres:9.6.8
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-user
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password  
        ports:
        - name: postgres-port
          containerPort: 5432
